config/routes.rb
Rails.application.routes.draw do
  devise_for :players

  resources :players, only: [ :index, :show ] do
    collection do
      get 'search(/:query)', action: :search, as: 'search', constraints: { query: /.*/ }
    end
  end

  resources :villas, only: [ :index, :show ] do
    resources :building_queue_items, only: [ :create, :destroy ]
    resources :research_queue_items, only: [ :create, :destroy ]
    resources :unit_queue_items, only: [ :create, :destroy ]

    resources :movements, only: [ :create, :index ], controller: 'villas/movements'
  end

  resources :movements, only: [ :index, :destroy ]
  resources :occupations, only: [ :destroy ]

  resources :messages, only: [ :new, :create, :index, :show, :destroy ]
  resources :reports, only: [ :index, :show, :destroy ]

  get '/map(/:x/:y)', to: 'map#show', as: :map

  root 'villas#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "Player"
  has_many :message_statuses
  has_and_belongs_to_many :receivers, class_name: "Player", join_table: "messages_receivers"

  validates_presence_of :sender, on: :create
  validates_presence_of :receivers, on: :create
  validates_presence_of :text, on: :create

  before_validation :remove_sender_from_receivers

  before_create :set_sent_at
  after_create :create_message_statuses
  after_create :increment_unread_counter_cache_for_player

  def remove_sender_from_receivers
    self.receivers = receivers.reject { |r| r.id == sender.id }
  end

  def set_sent_at
    self.sent_at = LaFamiglia.now
  end

  def create_message_statuses
    message_statuses.create(player: sender, read: true)

    receivers.each do |r|
      message_statuses.create(player: r, read: false)
    end
  end

  def increment_unread_counter_cache_for_player
    receivers.each do |r|
      r.increment! :unread_messages_count
    end
  end

  def status_for player
    message_statuses.find_by(player: player)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  power :messages

  before_action :set_message, only: [ :show, :destroy ]

  # GET /messages/1
  def show
  end

  def create
    @message = Message.create_with(sender: current_player)
                      .new(message_params)

    respond_to do |format|
      if @message.save
        format.html do
          redirect_back(fallback_location: root_path, notice: t('.created'))
        end
      else
        format.html do
          set_message_statuses
          render action: 'index'
        end
      end
    end
  end

  # GET /messages
  def index
    @message = Message.new
    set_message_statuses
  end

  # DELETE /messages/1
  def destroy
    @message_status.destroy
    redirect_to messages_url, notice: t('.deleted')
  end

  private

  def set_message
    @message = current_power.messages.find(params[:id])
    @message_status = @message.status_for current_player

    unless @message_status.read
      @message_status.mark_as_read!
      current_player.decrement :unread_messages_count
    end
  end

  def set_message_statuses
    @message_statuses = current_power.message_statuses.includes(:message)
                                                      .order('messages.sent_at DESC')
  end

  def message_params
    params.require(:message).permit(:text, :receiver_ids => [])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def message_form_for(object, *args, &block)
    options = args.extract_options!
    simple_form_for(object, *(args << options.merge(builder: MessageFormBuilder)), &block)
  end
end

app/views/messages/_form.html.erb
<%= message_form_for @message,
                    wrapper: :vertical_form,
                    html: { class: 'form-vertical' } do |f| %>
  <%= f.error_notification %>

  <%= f.players :receivers %>
  <%= f.input :text %>

  <div class="form-actions">
    <%= f.button :submit, t('.create'), class: 'btn-primary' %>
  </div>
<% end %>

app/views/messages/index.html.erb
<div class="row tabpanel">
  <div class="col-md-9 tab-content">
    <div id="messages" class="tab-pane active">
      <div class="page-header">
        <h1><%= t '.header' %></h1>
      </div>

      <% unless @message_statuses.empty? %>
        <table class="table table-striped messages">
          <tr>
            <th class="sent_at"><%= t '.sent_at' %></th>
            <th class="sender"><%= t '.sender' %></th>
            <th class="receivers"><%= t '.receivers' %></th>
            <th class="status"></th>
          </tr>
          <% @message_statuses.each do |status| %>
            <% message = status.message %>
            <tr>
              <td><%= link_to (l message.sent_at), message_path(message) %></td>
              <td><%= message.sender %></td>
              <td><%= message.receivers.join ', ' %></td>
              <td>
                <% unless status.read %>
                  <span class="glyphicon glyphicon-envelope"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p><%= t '.no_messages' %></p>
      <% end %>
    </div>

    <div id="new-message" class="tab-pane">
      <h3>
        <%= t '.new_message' %>
      </h3>

      <%= render 'form' %>
    </div>
  </div>

  <div class="col-md-3">
    <ul class="nav nav-pills nav-stacked" role="tablist">
      <li role="presentation" class="active">
        <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab"><%= t '.sidebar.messages' %></a>
      </li>
      <li role="presentation">
        <a href="#new-message" aria-controls="new-message" role="tab" data-toggle="tab"><%= t '.sidebar.new_message' %></a>
      </li>
    </ul>
  </div>
</div>

app/views/messages/show.html.erb
<h3>
  <%= t '.message_from', from: @message.sender %>
  <small><%= t '.sent_to', receivers: @message.receivers.join(', ') %></small>
</h3>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= l @message.sent_at %>
  </div>
  <div class="panel-body">
    <%= @message.text %>
  </div>
</div>

<%= link_to t('.delete'), message_url(@message),
                          method: :delete, class: "btn btn-primary" %>