config/routes.rb
Rails.application.routes.draw do
  devise_for :players

  resources :players, only: [ :index, :show ] do
    collection do
      get 'search(/:query)', action: :search, as: 'search', constraints: { query: /.*/ }
    end
  end

  resources :villas, only: [ :index, :show ] do
    resources :building_queue_items, only: [ :create, :destroy ]
    resources :research_queue_items, only: [ :create, :destroy ]
    resources :unit_queue_items, only: [ :create, :destroy ]

    resources :movements, only: [ :create, :index ], controller: 'villas/movements'
  end

  resources :movements, only: [ :index, :destroy ]
  resources :occupations, only: [ :destroy ]

  resources :messages, only: [ :new, :create, :index, :show, :destroy ]
  resources :reports, only: [ :index, :show, :destroy ]

  get '/map(/:x/:y)', to: 'map#show', as: :map

  root 'villas#index'
end

app/models/villa.rb
require_dependency 'extensions/queue_extension'
require_dependency 'extensions/building_queue_extension'
require_dependency 'extensions/research_queue_extension'
require_dependency 'extensions/unit_queue_extension'

class Villa < ActiveRecord::Base
  include LaFamiglia::Resources::Accessors
  include LaFamiglia::Buildings::Readers
  include LaFamiglia::Researches::Readers
  include LaFamiglia::Units::Accessors

  belongs_to :player

  has_many :building_queue_items, -> { extending QueueExtension, BuildingQueueExtension }, dependent: :delete_all,
           after_add: ->(v, i) { v.building_queue_items_count += 1 },
           after_remove: ->(v, i) { v.building_queue_items_count -= 1 }
  has_many :research_queue_items, -> { extending QueueExtension, ResearchQueueExtension }, dependent: :delete_all,
           after_add: ->(v, i) { v.research_queue_items_count += 1 },
           after_remove: ->(v, i) { v.research_queue_items_count -= 1 }
  has_many :unit_queue_items, -> { extending UnitQueueExtension }, dependent: :delete_all,
           after_add: ->(v, i) { v.unit_queue_items_count += 1 },
           after_remove: ->(v, i) { v.unit_queue_items_count -= 1 }
           # These hooks have to be used because Rails’ counter caching
           # only updates the database.

  has_many :outgoings,
           -> { includes(:target).order(:arrives_at) },
           class_name: 'Movement',
           foreign_key: 'origin_id'
  has_many :incomings,
           -> { includes(:origin).order(:arrives_at) },
           class_name: 'Movement',
           foreign_key: 'target_id'

  has_one :occupation, foreign_key: 'target_id'
  has_many :occupations, foreign_key: 'origin_id'

  before_create :set_default_values

  after_update :save_unit_queue

  def self.empty_coordinates(x_1 = 0, x_2 = LaFamiglia.config.max_x,
                             y_1 = 0, y_2 = LaFamiglia.config.max_y)
    x_range_length = x_2 - x_1 + 1
    y_range_length = y_2 - y_1 + 1
    max_villas_in_rectangle = x_range_length * y_range_length

    if Villa.in_rectangle(x_1, x_2, y_1, y_2).count < max_villas_in_rectangle
      if max_villas_in_rectangle == 1
        return [ x_1, y_1 ]
      end

      x_range_mean = x_1 + x_range_length / 2
      y_range_mean = y_1 + y_range_length / 2

      [ [ x_1, x_2, y_1, y_range_mean - 1 ],
        [ x_1, x_2, y_range_mean, y_2 ],
        [ x_1, x_range_mean - 1, y_1, y_2 ],
        [ x_range_mean, x_2, y_1, y_2 ] ]
      .sort_by { rand }
      .each do |p|
        if empty_coordinates = empty_coordinates(*p)
          return empty_coordinates
        end
      end
    end
  end

  def self.in_rectangle x_1, x_2, y_1, y_2
    where [ 'x BETWEEN ? AND ? AND y BETWEEN ? AND ?',
            x_1, x_2, y_1, y_2 ]
  end

  def self.create_for player
    return nil unless (coordinates = empty_coordinates)

    transaction do
      new_villa = Villa.create(x: coordinates[0],
                  y: coordinates[1],
                  name: I18n.t('villa.default_name'),
                  player: player)

      player.recalc_points!

      new_villa
    end
  end

  def self.max_points
    @@max_points ||= LaFamiglia.buildings.inject(0) do |acc, b|
      acc + b.points(b.maxlevel)
    end
  end

  def set_default_values
    self.processed_until = LaFamiglia.now
    self.is_occupied = false
    self.building_queue_items_count = 0
    self.research_queue_items_count = 0
    self.unit_queue_items_count = 0

    self.storage_capacity = 100
    self.resource_1 = self.resource_2 = self.resource_3 = 0

    self.building_1 = 1
    self.building_2 = 0

    self.research_1 = 0

    self.supply = 100
    self.used_supply = 0
    self.unit_1 = 0
    self.unit_2 = 0

    recalc_points
  end

  def save_unit_queue
    if unit_queue_items_count > 0
      if (first = unit_queue_items.first).changed?
        first.save(validate: false)
      end
    end
  end

  def recalc_points
    self.points = LaFamiglia.buildings.inject(0) do |sum, b|
      sum + b.points(level b)
    end
  end

  def process_until!(time)
    points_changed = false
    finished_items = []

    if building_queue_items_count > 0
      finished_items.concat building_queue_items.finished_until(time)
    end

    if research_queue_items_count > 0
      finished_items.concat research_queue_items.finished_until(time)
    end

    if unit_queue_items_count > 0
      finished_items.concat unit_queue_items.finished_until(time)
    end

    if finished_items.length > 0
      finished_items.sort_by! { |i| i.completed_at }

      transaction do
        finished_items.each do |i|
          process_virtually_until! i.completed_at

          case i
          when BuildingQueueItem
            increment(i.building.key)
            recalc_points
            points_changed = true
            building_queue_items.destroy i
          when ResearchQueueItem
            increment(i.research.key)
            research_queue_items.destroy i
          when UnitQueueItem
            unit_queue_items.destroy i
          end
        end

        save(validate: false)
        player.recalc_points! if points_changed
      end
    end

    process_virtually_until! time
  end

  # Processes resource gains and recruiting of units without saving
  # the results to the database.
  #
  # Relies on the fact that the difference between self.processed_until
  # and time makes sense for unit_queue_items.first.
  #
  # Must not be called more than once in a row as otherwise the amount
  # of units recruited would be incorrect due to unit_queue_items.first
  # not being saved in between.
  def process_virtually_until! time
    time_diff = time - self.processed_until

    if time_diff != 0
      add_resources!(resource_gains time_diff)

      if unit_queue_items_count > 0
        add_units!(unit_queue_items.first.recruit_units_between!(self.processed_until, time))
      end
    end

    self.processed_until = time
  end

  def add_resources!(resources)
    self.resource_1 = [ self.resource_1 + resources[:resource_1], self.storage_capacity ].min
    self.resource_2 = [ self.resource_2 + resources[:resource_2], self.storage_capacity ].min
    self.resource_3 = [ self.resource_3 + resources[:resource_3], self.storage_capacity ].min
  end

  def subtract_resources!(resources)
    self.resource_1 -= resources[:resource_1]
    self.resource_2 -= resources[:resource_2]
    self.resource_3 -= resources[:resource_3]
  end

  def has_resources?(resources)
    self.resource_1 >= resources[:resource_1] &&
        self.resource_2 >= resources[:resource_2] &&
        self.resource_3 >= resources[:resource_3]
  end

  def add_units!(units)
    units.each_pair do |key, number|
      self[key] += number
    end
  end

  def occupied?
    is_occupied
  end

  def has_supply?(supply)
    self.used_supply + supply <= self.supply
  end

  def level building_or_research
    self[building_or_research.key]
  end

  def enqueued_count building
    if building_queue_items_count > 0
      building_queue_items.enqueued_count(building)
    else
      0
    end
  end

  def virtual_building_level building
    self[building.key] + enqueued_count(building)
  end

  def enqueued_researches_count research
    if research_queue_items_count > 0
      research_queue_items.enqueued_count(research)
    else
      0
    end
  end

  def virtual_research_level research
    self[research.key] + enqueued_researches_count(research)
  end

  def unit_number unit
    self[unit.key]
  end

  # Beware that virtual has a different meaning here than it has in
  # virtual_building_level. Since building levels are updated by the event
  # handler they are always current when loaded from the database. Virtual
  # means: the building level has not yet been reached.
  # Since unit numbers are not regularly updated by the event handler values
  # loaded from the database may belong to the past. Virtual means: the
  # database does not get changed when this number is calculated.
  def virtual_unit_number unit
    self[unit.key] + unit_queue_items.enqueued_count_until(unit, LaFamiglia.now)
  end

  def resource_gains time_diff
    {
      resource_1: time_diff * 0.01,
      resource_2: time_diff * 0.01,
      resource_3: time_diff * 0.01
    }
  end

  def duration_of_occupation
    (1.0 + points.to_f / Villa.max_points) * LaFamiglia.config.base_duration_of_occupation
  end

  def to_s
    "#{name} (#{x}|#{y})"
  end
end

app/controllers/villas/movements_controller.rb
class Villas::MovementsController < ApplicationController
  before_action :set_villa, only: [ :index, :create ]

  # GET /movements
  def index
    @outgoings   = current_villa.outgoings
    @occupations = current_villa.occupations
  end

  # POST /movements
  def create
    @movement = AttackMovement.create_with(origin: current_villa).new(movement_params)

    if @movement.save
      notify_event_handler @movement.arrives_at
      redirect_to :back, notice: I18n.t('movements.created')
    else
      render action: 'new'
    end
  end

  private

  def set_villa
    @villa = current_player.villas.find(params[:villa_id])

    @current_villa = @villa
    @current_villa.process_until! LaFamiglia.now
    session[:current_villa] = @villa.id
  end

  def movement_params
    params.require(:movement).permit(:target_id, :unit_1, :unit_2)
  end
end

app/controllers/villas_controller.rb
class VillasController < ApplicationController
  power :villas

  skip_before_action :check_for_villa!
  before_action :set_villa, only: [ :show ]
  before_action :check_for_villa!

  # GET /villas/1
  def show
    render 'occupied' if current_villa.occupied?
  end

  # GET /villas
  def index
    @villas = current_power.villas.includes(:unit_queue_items)
  end

  private

  def set_villa
    @villa = current_power.villas.find(params[:id])

    @current_villa = @villa
    @current_villa.process_until! LaFamiglia.now
    session[:current_villa] = @villa.id
  end
end

app/helpers/villa_helper.rb
module VillaHelper
  def coordinates villa
    "(#{villa.x}|#{villa.y})"
  end

  def resources villa
    render partial: 'common/resources', locals: { villa: villa,
                                                  resource_gains: villa.resource_gains(3600) }
  end

  def costs costs
    render partial: 'common/costs', locals: { resource_1: costs[:resource_1],
                                              resource_2: costs[:resource_2],
                                              resource_3: costs[:resource_3] }
  end
end

app/helpers/villas/movements_helper.rb
module Villas::MovementsHelper
end

app/views/villas/index.html.erb
<h2><%= t '.header' %></h2>

<h4>Here you can view your villas. Currently their number is <%= @villas.count %>.</h4>

<table class="table table-striped table-condensed">
  <tr>
    <th><%= t '.name' %></th>
    <th><%= t '.points' %></th>
    <th><%= t '.show_on_map' %></th>
    <% LaFamiglia.units.each do |u| %>
      <th><%= u.name %></th>
    <% end %>
  </tr>
  <% @villas.each do |v| %>
    <tr>
      <td><%= link_to v.name, villa_url(v) %></td>
      <td><%= v.points %></td>
      <td><%= link_to coordinates(v), map_url(x: v.x, y: v.y) %></td>
      <% LaFamiglia.units.each do |u| %>
        <td><%= v.virtual_unit_number u %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/villas/occupied.html.erb
<h2>
  <%= current_villa.name %> <%= coordinates current_villa %>
</h2>

<div class="occupied-header">
  <p>
    <%= t '.villa_occupied' %>
  </p>
  <p>
    <%= t '.villa_lost_in_html', lost_in: countdown_to(current_villa.occupation.succeeds_at) %>
  </p>
</div>

<div class="occupied-info">
  <p>
    <%= t '.villa_occupied_by', villa: current_villa.occupation.origin %>
  </p>

  <p>
    <%= t '.occupation_will_end', end_of_occupation: l(current_villa.occupation.succeeds_at) %>
  </p>

  <p>
    <%= t '.takeover_warning', occupied_by: current_villa.occupation.origin.player %>
  </p>
</div>

app/views/villas/show.html.erb
<div class="row tabpanel">
  <div class="col-md-9 tab-content">
    <div class="tab-pane active">
      <h2>
        <%= current_villa.name %> <%= coordinates current_villa %>
      </h2>

      <div>
        <%= t '.info_html', coordinates: coordinates(current_villa), points: current_villa.points %>
      </div>

      <h3>
        <%= t '.buildings' %>
      </h3>

      <table class="col-md-8 table table-striped">
        <tr>
          <th><%= t 'building' %></th>
          <th><%= t '.level' %></th>
          <th><%= t '.points' %></th>
          <th><%= t '.costs' %></th>
          <th><%= t '.build_time' %></th>
          <th><%= t '.build!' %></th>
        </tr>
        <% LaFamiglia.buildings.each do |b| %>
          <tr>
            <td><%= b.name %></td>
            <td><%= current_villa.level(b) %> (<%= current_villa.virtual_building_level(b) %>)</td>
            <td><%= b.points(current_villa.level(b)) %></td>
            <% if current_villa.virtual_building_level(b) < b.maxlevel %>
              <td><%= costs b.costs(current_villa.virtual_building_level(b)) %></td>
              <td><%= b.build_time current_villa.virtual_building_level(b) %></td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
            <td>
              <%= link_to_build_start b %>
            </td>
          </tr>
        <% end %>
      </table>

      <h3>
        <%= t '.researches' %>
      </h3>

      <table class="col-md-8 table table-striped">
        <tr>
          <th><%= t 'research' %></th>
          <th><%= t '.level' %></th>
          <th><%= t '.costs' %></th>
          <th><%= t '.research_time' %></th>
          <th><%= t '.research!' %></th>
        </tr>
        <% LaFamiglia.researches.each do |r| %>
          <tr>
            <td><%= r.name %></td>
            <td><%= current_villa.level(r) %> (<%= current_villa.virtual_research_level(r) %>)</td>
            <% if current_villa.virtual_research_level(r) < r.maxlevel %>
              <td><%= costs r.costs(current_villa.virtual_research_level(r)) %></td>
              <td><%= r.research_time current_villa.virtual_research_level(r) %></td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
            <td>
              <%= link_to_research_start r %>
            </td>
          </tr>
        <% end %>
      </table>

      <h3>
        <%= t '.units' %>
      </h3>

      <table class="col-md-8 table table-striped">
        <tr>
          <th><%= t 'unit' %></th>
          <th><%= t '.number' %></th>
          <th><%= t '.costs' %></th>
          <th><%= t 'supply' %></th>
          <th><%= t '.build_time' %></th>
          <th><%= t '.build!' %></th>
        </tr>
        <% LaFamiglia.units.each do |u| %>
          <tr>
            <td><%= u.name %></td>
            <td><%= current_villa.unit_number(u) %></td>
            <td><%= costs u.costs %></td>
            <td><%= u.supply %></td>
            <td><%= u.build_time %></td>
            <td>
              <% [ 1, 5, 20, 100 ].each do |n| %>
                <%= link_to_recruit_start u, n %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>

      <% if current_villa.building_queue_items_count > 0 %>
        <h3>
          <%= t '.building_queue' %>
        </h3>

        <table class="col-md-8 table table-striped">
          <tr>
            <th><%= t 'building' %></th>
            <th><%= t '.build_time' %></th>
            <th><%= t '.completion_time' %></th>
            <th></th>
            <th><%= t '.cancel' %></th>
          </tr>
          <% current_villa.building_queue_items.each do |i| %>
            <tr>
              <td><%= i.building_id %></td>
              <td><%= i.build_time %>
              <td><%= l i.completed_at %></td>
              <td><%= countdown_to i.completed_at %></td>
              <td>
                <%= link_to_build_cancel i %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>

      <% if current_villa.research_queue_items_count > 0 %>
        <h3>
          <%= t '.research_queue' %>
        </h3>

        <table class="col-md-8 table table-striped">
          <tr>
            <th><%= t 'research' %></th>
            <th><%= t '.research_time' %></th>
            <th><%= t '.completion_time' %></th>
            <th></th>
            <th><%= t '.cancel' %></th>
          </tr>
          <% current_villa.research_queue_items.each do |i| %>
            <tr>
              <td><%= i.research_id %></td>
              <td><%= i.research_time %>
              <td><%= l i.completed_at %></td>
              <td><%= countdown_to i.completed_at %></td>
              <td>
                <%= link_to_research_cancel i %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>

      <% if current_villa.unit_queue_items_count > 0 %>
        <h3>
          <th><%= t '.unit_queue' %></th>
        </h3>

        <table class="col-md-8 table table-striped">
          <tr>
            <th><%= t 'unit' %></th>
            <th><%= t '.number' %></th>
            <th><%= t '.build_time' %></th>
            <th><%= t '.completion_time' %></th>
            <th></th>
            <th><%= t '.cancel' %></th>
          </tr>
          <% current_villa.unit_queue_items.each do |i| %>
            <tr>
              <td><%= i.unit_id %></td>
              <td><%= i.number %></td>
              <td><%= i.build_time %>
              <td><%= l i.completed_at %></td>
              <td><%= countdown_to i.completed_at %></td>
              <td>
                <%= link_to_recruit_cancel i %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>
    </div>
  </div>

  <div class="col-md-3">
    <ul class="nav nav-pills nav-stacked" role="tablist">
      <li role="presentation" class="active">
        <a href="#" aria-controls="overview" role="tab"><%= t '.sidebar.overview' %></a>
      </li>
      <li role="presentation">
        <a href="<%= villa_movements_url current_villa %>" aria-controls="troops" role="tab"><%= t '.sidebar.troops' %></a>
      </li>
    </ul>
  </div>
</div>