config/routes.rb
Rails.application.routes.draw do
  devise_for :players

  resources :players, only: [ :index, :show ] do
    collection do
      get 'search(/:query)', action: :search, as: 'search', constraints: { query: /.*/ }
    end
  end

  resources :villas, only: [ :index, :show ] do
    resources :building_queue_items, only: [ :create, :destroy ]
    resources :research_queue_items, only: [ :create, :destroy ]
    resources :unit_queue_items, only: [ :create, :destroy ]

    resources :movements, only: [ :create, :index ], controller: 'villas/movements'
  end

  resources :movements, only: [ :index, :destroy ]
  resources :occupations, only: [ :destroy ]

  resources :messages, only: [ :new, :create, :index, :show, :destroy ]
  resources :reports, only: [ :index, :show, :destroy ]

  get '/map(/:x/:y)', to: 'map#show', as: :map

  root 'villas#index'
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :player

  serialize :data, JSON

  validates_inclusion_of :read, in: [ true, false ]

  after_create :increment_unread_counter_cache_for_player

  def self.report_data *keys
    keys.each do |k|
      define_method k do
        self.data[k]
      end
    end
  end

  def increment_unread_counter_cache_for_player
    player.increment! :unread_reports_count
  end

  def mark_as_read!
    update_attribute :read, true
    player.decrement! :unread_reports_count
  end

  def data
    @data ||= self[:data].with_indifferent_access
  end

  def origin
    @origin ||= Villa.find data[:origin_id]
  end

  def target
    @target ||= Villa.find data[:target_id]
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  power :reports

  before_action :set_report, only: [ :show, :destroy ]

  # GET /reports/1
  def show
  end

  # GET /reports
  def index
    @reports = current_power.reports.order 'reports.delivered_at DESC'
  end

  # DELETE /reports/1
  def destroy
    @report.destroy
    redirect_to reports_url, notice: t('.deleted')
  end

  private

  def set_report
    @report = current_power.reports.find(params[:id])
    @report.mark_as_read! unless @report.read
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<div class="page-header">
  <h1><%= t '.header' %></h1>
</div>

<% unless @reports.empty? %>
  <table class="table table-striped">
    <tr>
      <th><%= t '.delivered_at' %></th>
      <th><%= t '.title' %></th>
      <th></th>
    </tr>
    <% @reports.each do |report| %>
      <tr>
        <td><%= l report.delivered_at %></td>
        <td><%= link_to report.title, report_path(report) %></td>
        <td>
          <% unless report.read %>
            <span class="glyphicon glyphicon-envelope"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p><%= t '.no_reports' %></p>
<% end %>

app/views/reports/show.html.erb
<%= render @report %>

<%= link_to t('.delete'), report_url(@report),
                          method: :delete, class: "btn btn-primary" %>